server:
  port: 8083

spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/SSO
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect

keycloak:
  server:
    contextPath: /auth
    adminUser:
      username: habibbank
      password: habibbank
    realmImportFile: baeldung-realm.json
